// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624113511_DoubleToDecimal")]
    partial class DoubleToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Domain.Entities.MetalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Высокоточный раскрой листового проката до 20мм.",
                            PriceFrom = 12.50m,
                            Title = "Лазерная резка ЧПУ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Радиусная и профильная гибка на гидравлических прессах.",
                            PriceFrom = 6.80m,
                            Title = "Гибка листового металла"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MetalServiceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MetalServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetalServiceId");

                    b.ToTable("MetalServiceImage");
                });

            modelBuilder.Entity("Domain.Entities.UnliquidProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnliquidProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Лист горячекатаный, марка Ст3сп, размер 1500х6000.",
                            Name = "Стальной лист ГК 10мм",
                            Price = 450.00m,
                            Quantity = "4 шт"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Остатки после производства металлоконструкций. Длина хлыстов 3м.",
                            Name = "Труба профильная 40х40х3",
                            Price = 12.80m,
                            Quantity = "25 шт"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UnliquidProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnliquidProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnliquidProductId");

                    b.ToTable("UnliquidProductImage");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.MetalServiceImage", b =>
                {
                    b.HasOne("Domain.Entities.MetalService", "MetalService")
                        .WithMany("Images")
                        .HasForeignKey("MetalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetalService");
                });

            modelBuilder.Entity("Domain.Entities.UnliquidProductImage", b =>
                {
                    b.HasOne("Domain.Entities.UnliquidProduct", "UnliquidProduct")
                        .WithMany("Images")
                        .HasForeignKey("UnliquidProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnliquidProduct");
                });

            modelBuilder.Entity("Domain.Entities.MetalService", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Domain.Entities.UnliquidProduct", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
